Rails.application.routes.draw do
  scope '/api/version1' do
    resources :tdlists
  end
  # below autogenerated by controller command
  # get 'tdlists/index'
  # get 'tdlists/create'
  # get 'tdlists/update'
  # get 'tdlists/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
